jobs:
  build:
    concurrency:
      cancel-in-progress: true
      group: android-${{ matrix.working-directory }}-${{ github.ref }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out Git repository
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'
    - continue-on-error: true
      name: Accept licenses
      run: /bin/bash -c "yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        > /dev/null"
    - continue-on-error: true
      id: cache-node-modules-svg
      name: Restore svg node_modules from cache
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-node-modules-svg-${{ hashFiles('yarn.lock') }}
        path: 'node_modules

          '
        restore-keys: '${{ runner.os }}-node-modules-svg

          '
    - continue-on-error: true
      name: Install svg node_modules
      run: yarn install --frozen-lockfile
    - continue-on-error: true
      id: cache-node-modules-app
      name: Restore app node_modules from cache
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-node-modules-${{ matrix.working-directory }}-${{ hashFiles(format('{0}/yarn.lock',
          matrix.working-directory)) }}
        path: '${{ matrix.working-directory }}/node_modules

          '
        restore-keys: '${{ runner.os }}-node-modules-${{ matrix.working-directory
          }}-

          '
    - continue-on-error: true
      name: Install app node_modules
      run: yarn install --frozen-lockfile
      working-directory: ${{ matrix.working-directory }}
    - continue-on-error: true
      name: Restore build from cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-build5-${{ matrix.working-directory }}-${{ hashFiles('**/*.gradle*',
          '**/gradle-wrapper.properties', 'android/build.gradle', format('{0}/node_modules/react-native/sdks/.hermesversion',
          matrix.working-directory)) }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          android/build

          android/.cxx

          ${{ matrix.working-directory }}/android/build

          ${{ matrix.working-directory }}/android/.cxx

          ${{ matrix.working-directory }}/android/.gradle

          ${{ matrix.working-directory }}/android/app/build

          ${{ matrix.working-directory }}/android/app/.cxx

          ${{ matrix.working-directory }}/node_modules/react-native/ReactAndroid/build

          ${{ matrix.working-directory }}/node_modules/react-native/ReactAndroid/hermes-engine/build

          ${{ matrix.working-directory }}/node_modules/react-native/ReactAndroid/hermes-engine/.cxx

          '
    - continue-on-error: true
      name: Build app
      run: ./gradlew assembleDebug --build-cache --console=plain -PreactNativeArchitectures=arm64-v8a
      working-directory: ${{ matrix.working-directory }}/android
    strategy:
      matrix:
        working-directory:
        - Example
        - FabricExample
name: Test Android build
on:
  repository_dispatch:
    types: trigger-ga___android-build-test.yml
