jobs:
  build:
    concurrency:
      cancel-in-progress: true
      group: ios-${{ matrix.working-directory }}-${{ github.ref }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out Git repository
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Use latest stable Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - continue-on-error: true
      name: Restore react-native-svg node_modules from cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-node-modules-svg-${{ hashFiles('yarn.lock') }}
        path: node_modules
        restore-keys: ${{ runner.os }}-node-modules-svg-
    - continue-on-error: true
      name: Install react-native-svg node_modules
      run: yarn install --frozen-lockfile
    - continue-on-error: true
      name: Restore app node_modules from cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-node-modules-${{ matrix.working-directory }}-${{ hashFiles(format('{0}/yarn.lock',
          matrix.working-directory)) }}
        path: ${{ matrix.working-directory }}/node_modules
        restore-keys: ${{ runner.os }}-node-modules-${{ matrix.working-directory }}-
    - continue-on-error: true
      name: Install app node_modules
      run: yarn install --frozen-lockfile
      working-directory: ${{ matrix.working-directory }}
    - continue-on-error: true
      name: Restore Pods from cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-pods-${{ matrix.working-directory }}-${{ hashFiles(format('{0}/ios/Podfile.lock',
          matrix.working-directory)) }}
        path: '${{ matrix.working-directory }}/ios/Pods

          ~/Library/Caches/CocoaPods

          ~/.cocoapods

          '
    - continue-on-error: true
      name: Install Pods
      run: pod install
      working-directory: ${{ matrix.working-directory }}/ios
    - continue-on-error: true
      name: Restore build artifacts from cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-ios-derived-data-${{ matrix.working-directory }}-${{
          hashFiles(format('{0}/ios/Podfile.lock', matrix.working-directory)) }}
        path: ~/Library/Developer/Xcode/DerivedData
    - continue-on-error: true
      name: Build app
      run: npx react-native@latest run-ios --simulator="iPhone 14 Pro" --mode Debug
        --verbose --terminal /bin/zsh
      working-directory: ${{ matrix.working-directory }}
    strategy:
      fail-fast: false
      matrix:
        working-directory:
        - Example
        - FabricExample
name: Test iOS build
on:
  repository_dispatch:
    types: trigger-ga___ios-build-test.yml
