jobs:
  build:
    concurrency:
      cancel-in-progress: true
      group: js-${{ github.ref }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Use Node.js 18
      uses: actions/setup-node@v2
      with:
        cache: yarn
        cache-dependency-path: yarn.lock
        node-version: 18
    - continue-on-error: true
      name: Install node dependencies
      run: yarn
    - continue-on-error: true
      name: Build
      run: yarn bob
    - continue-on-error: true
      name: Test and lint
      run: yarn test
    - continue-on-error: true
      name: Build Example App
      run: yarn && yarn tsc
      working-directory: Example/
name: Test JS build
on:
  repository_dispatch:
    types: trigger-ga___js-build-test.yml
